###
POST {{url}}/api/v1/auth/signup

{
  "fullname": ".",
  "username": "valid@gmail.com",
  "password": "Bruh0!0!",
  "confirm-password": "Bruh0!0!"
}

###
POST {{url}}/api/v1/auth/login

{
  "username": "asd10",
  "password": "asd"
}

